image: Visual Studio 2022

environment:
  PYTHON: "C:\\Python311"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python -m pip install --upgrade pip
  - pip install flask
  - pip install gunicorn
  - pip install requests
  - pip install flask-bootstrap
  - pip install flask-wtf
  - pip install pillow
  - pip install tensorflow
  - pip install keras

before_build:
  - powershell -Command "& {chmod +x ./flaskapp/st.sh}"

build: off

test_script:
  - cd flaskapp
  - bash st.sh
