image: Visual Studio 2022

environment:
  PYTHON: "C:\\Python311"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python -m pip install --upgrade pip
  - pip install flask gunicorn requests

build: off

test_script:
  - cd flaskapp
  - bash st.sh
